all:
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/Ansible-Practice/Ansible-KeyPair-New.pem
    ansible_user: datascientest
    ansible_password: Datascientest2022
    ansible_become_pass: Datascientest2022
    ansible_python_interpreter: /usr/bin/python3.12
  children:
    datascientest_app:
      children:
        databaseserver:
          hosts:
            serverdatabase1.datascientest.com:
              ansible_host: 13.36.234.120
              ansible_user: ubuntu  # You can keep this if the user is different from the global one

        webserver:
          hosts:
            serverweb1.datascientest.com:
              ansible_host: 15.237.176.29
              ansible_user: ubuntu  # Same here; this will override global ansible_user if needed

    dev:
      hosts:
        client-dev:
          ansible_host: 13.36.234.120
          ansible_user: ubuntu
          env: dev

    prod:
      hosts:
        client-prod:
          ansible_host: 15.237.176.29
          ansible_user: ubuntu
          env: prod

    test:
      hosts:
        client-test:
          ansible_host: 15.188.180.68
          ansible_user: ubuntu
          env: test