---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install MySQL on Debian-based systems
  ansible.builtin.apt:
    name: mysql-server
    state: present
  when: ansible_facts.pkg_mgr == "apt"

- name: Start MySQL service
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: true
