- hosts: production
  become: true
  vars:
    wp_version: 5.7.1
    wp_webserver: nginx
    wp_mysql_db: "database"
    wp_mysql_user: "datascientest"
    wp_mysql_password: "mysql_pass"
    wp_admin_email: "admin@datascientest.fr"
    wp_sitename: "demo.com"
    wp_install_dir: "/var/www/demo.com"
  roles:
    - wordpress
