---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: fallewi/ansible-molecule:datasientest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
